apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    name: guestbook-ui
    project: argocd
    env: test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: nginx:mainline-alpine3.18-slim
        name: guestbook-ui
        ports:
        - containerPort: 80
